### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by Ksurajjordan23** [Romaine/python-suite#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [python-suite](https://github.com/Romaine/python-suite) package 0.3.2

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:183

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:351:12)
    at checkGrammar (/packages/python-suite/lib/python-suite.coffee:32:33)
    at Function.simpleDispatch (/Users/apple/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:1172021)
    at Emitter.emit (/Users/apple/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:1173462)
    at Workspace.didActivatePaneContainer (/Users/apple/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:424205)
    at Dock.subscriptions.l.paneContainer.onDidActivatePane (/Users/apple/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:468986)
    at Function.simpleDispatch (/Users/apple/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:1172021)
    at Emitter.emit (/Users/apple/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:1173462)
    at PaneContainer.didActivatePane (/Users/apple/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:446391)
    at Pane.activate (/Users/apple/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:463720)
    at Pane.focus (/Users/apple/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:455173)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -3:05.5.0 application:add-project-folder (input.hidden-input)
     -2:58.5.0 command-palette:toggle (div.tool-panel.tree-view)
     -2:53.8.0 run-python-simply:toggle (div.tool-panel.tree-view)
     -2:45.7.0 core:save (div.tool-panel.tree-view)
     -2:41.5.0 core:save-as (div.tool-panel.tree-view)
     -0:16.1.0 command-palette:toggle (input.hidden-input)
     -0:13.9.0 Python run: run-f6 (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-debugger-python 0.7.3 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-python-run 0.9.7 
build 0.70.0 
build-python 0.9.3 
busy-signal 2.0.1 
docblock-python 0.14.1 
hey-pane 1.1.2 
ide-python 1.4.1 
intentions 1.1.5 
linter 2.3.0 
linter-python 3.1.2 
linter-ui-default 1.7.1 
python-black 0.7.0 
python-debugger 0.2.0 
python-indent 1.1.7 
python-isort 0.0.7 
python-runner 1.2.1 
python-snippets 1.9.0 
python-suite 0.3.2 
python-tools 0.6.9 
run-python-simply 0.6.0 
```

**Comment by kirogi97** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Kali GNU/Linux
**Thrown From**: [python-suite](https://github.com/Romaine/python-suite) package 0.3.2


### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:183

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:351:12)
    at checkGrammar (/packages/python-suite/lib/python-suite.coffee:32:33)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1206583)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1208024)
    at Workspace.didActivatePaneContainer (/usr/share/atom/resources/app/static/<embedded>:11:422729)
    at Dock.subscriptions.l.paneContainer.onDidActivatePane (/usr/share/atom/resources/app/static/<embedded>:11:467515)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1206583)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1208024)
    at PaneContainer.didActivatePane (/usr/share/atom/resources/app/static/<embedded>:11:444920)
    at Pane.activate (/usr/share/atom/resources/app/static/<embedded>:11:462249)
    at Pane.focus (/usr/share/atom/resources/app/static/<embedded>:11:453686)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -1:46.7.0 core:save (input.hidden-input)
  3x -1:05.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:52.3.0 core:move-right (input.hidden-input)
     -0:51 editor:newline (input.hidden-input)
     -0:42.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
aligner-python 1.2.0 
atom-autocomplete-python 5.0.0 
atom-clock 0.1.17 
atom-python-run 0.9.7 
atom-python-test 0.10.0 
atom-python-virtualenv 1.0.2 
autocomplete-python 1.14.1 
autocomplete-python-jedi 1.10.3-0 
awesome-python-snippets 0.3.0 
better-python-snippets 1.0.0 
build 0.70.0 
build-python 0.9.3 
busy-signal 2.0.1 
docblock-python 0.15.0 
ide-python 1.4.1 
python-black 0.7.0 
python-debugger 0.2.0 
python-docstring 0.0.3 
python-indent 1.2.3 
python-isort 0.0.7 
python-line-profiler 0.3.2 
python-mrigor 2.1.3 
python-nosetests 0.2.0 
python-requirements 0.2.1 
python-runner 1.2.1 
python-snippets 1.9.0 
python-suite 0.3.2 
python-tools 0.6.9 
python-yapf 0.14.0 
rhino-python 0.8.4 
run-python-simply 0.6.0 
```
