### ISSUE TITLE
Uncaught Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by dfdias** [Romaine/python-suite#12]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 4.1.4
**OS**: "Arch Linux"
**Thrown From**: [python-suite](https://github.com/Romaine/python-suite) package 0.3.2

### Stack Trace

Uncaught Cannot call write after a stream was destroyed

```
At events.js:167

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:406:19)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at checkGrammar (/packages/python-suite/lib/python-suite.coffee:32:33)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/lib/atom/src/workspace.js:429:20)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/usr/lib/atom/src/workspace-center.js:17:14)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at PaneContainer.didChangeActiveItemOnPane (/usr/lib/atom/src/pane-container.js:281:20)
    at Pane.setActiveItem (/usr/lib/atom/src/pane.js:440:42)
    at Pane.activateItem (/usr/lib/atom/src/pane.js:579:12)
    at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/usr/lib/atom/node_modules/tabs/lib/tab-bar-view.js:808:16)
    at TabBarView.module.exports.TabBarView.onDrop (/usr/lib/atom/node_modules/tabs/lib/tab-bar-view.js:659:23)
```

### Commands

```
  3x -3:26.9.0 core:close (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  6x -3:21.9.0 core:backspace (input.hidden-input)
  2x -3:06.0 core:undo (input.hidden-input)
     -2:59.5.0 core:backspace (input.hidden-input)
     -2:57.8.0 core:save (input.hidden-input)
     -2:41.8.0 application:new-file (input.hidden-input)
  4x -2:35 core:backspace (input.hidden-input)
     -2:29.4.0 editor:newline (input.hidden-input)
  2x -2:26.2.0 window:decrease-font-size (input.hidden-input)
  2x -2:24.5.0 window:increase-font-size (input.hidden-input)
  2x -2:20.7.0 core:save (input.hidden-input)
  2x -1:12.9.0 window:toggle-full-screen (input.hidden-input)
  2x -1:02.2.0 docblock-python:generate_docblock (input.hidden-input)
     -0:34.6.0 python-requirements:toggle (input.hidden-input)
     -0:21.9.0 core:backspace (input.hidden-input)
     -0:17.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-doxit 0.2.0 
atom-python-run 0.9.7 
autocomplete-python 1.14.0 
awesome-python-snippets 0.3.0 
build 0.70.0 
build-python 0.9.3 
busy-signal 2.0.1 
docblock-python 0.14.1 
doxygen-snippets 0.1.1 
ide-python 1.4.1 
language-doxygen 0.7.0 
python-docstring 0.0.3 
python-indent 1.2.3 
python-requirements 0.2.1 
python-snippets 1.9.0 
python-suite 0.3.2 
python-tools 0.6.9 
terminal-plus 0.14.5 
vk-terminal 3.0.1 
```

**Comment by johnmee** [comment]
python-suite package is the culprit.
