### ISSUE TITLE
Uncaught Error: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by SukumarGuntru** [Romaine/python-suite#14]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [python-suite](https://github.com/Romaine/python-suite) package 0.3.2

### Stack Trace

Uncaught Error: Cannot call write after a stream was destroyed

```
At events.js:171

Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at checkGrammar (/packages/python-suite/lib/python-suite.coffee:32:33)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1201250)
    at Emitter.emit (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1202691)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:424872)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:44778
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1201250)
    at Emitter.emit (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1202691)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:447205)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:446682)
    at Pane.activate (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:464100)
    at Pane.focus (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:455543)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
```

### Non-Core Packages

```
aligner-python 1.2.0 
atom-clock 0.1.18 
atom-python-run 0.9.7 
atom-python-test 1.0.1 
autocomplete-python 1.16.0 
awesome-python-snippets 0.3.0 
build 0.70.0 
build-python 0.12.1 
busy-signal 2.0.1 
hey-pane 1.2.0 
Hydrogen 2.14.1 
ide-python 1.5.0 
kite 0.184.0 
platformio-ide-terminal 2.10.0 
python-debugger 0.2.0 
python-docstring 0.0.3 
python-indent 1.2.6 
python-line-profiler 0.3.2 
python-mrigor 2.1.3 
python-requirements 1.2.0 
python-snippets 1.9.0 
python-suite 0.3.2 
python-tools 0.6.9 
run-python-simply 0.6.0 
scroll-through-time 0.3.1 
```

**Comment by pavango** [comment]
y it is happaning like this , my text editor iss showing alart issus , by installing your pakage

**Comment by Romaine** [comment]
My apologies, this addon is unsupported.  I thought I removed it. I'll
remove it now.

**Comment by laurenmichaeljones** [comment]
it needs work and it is still up?

**Comment by Romaine** [comment]
Thanks for reminding me, I went to do it last time but I didn't have access
to the repo and the auth and couldn't remember how to change the settings.
I should have both now so I'll unpublish it today.  I'd say use the package
called kite, that's what I was going for at the time.
