### ISSUE TITLE
Uncaught Error: This socket is closed

### ISSUE THREAD

**Issue by amrf** [Romaine/python-suite#3]
[Enter steps to reproduce below:]

1. Click on a python script tab coming from a xml tab

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.1
**Thrown From**: [python-suite](https://github.com/Romaine/python-suite) package, v0.3.2

### Stack Trace

Uncaught Error: This socket is closed

```
At events.js:160

Error: This socket is closed
    at Socket._writeGeneric (net.js:673:19)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at checkGrammar (/Users/amrf/.atom/packages/python-suite/lib/python-suite.coffee:32:33)
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/ln/yzs4x7g14wj2f180jqvsbz_w0000gp/T/AppTranslocation/6FA4FDB5-C661-4C99-A026-A5CB8AF6E3C1/d/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/ln/yzs4x7g14wj2f180jqvsbz_w0000gp/T/AppTranslocation/6FA4FDB5-C661-4C99-A026-A5CB8AF6E3C1/d/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /private/var/folders/ln/yzs4x7g14wj2f180jqvsbz_w0000gp/T/AppTranslocation/6FA4FDB5-C661-4C99-A026-A5CB8AF6E3C1/d/Atom.app/Contents/Resources/app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/ln/yzs4x7g14wj2f180jqvsbz_w0000gp/T/AppTranslocation/6FA4FDB5-C661-4C99-A026-A5CB8AF6E3C1/d/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/ln/yzs4x7g14wj2f180jqvsbz_w0000gp/T/AppTranslocation/6FA4FDB5-C661-4C99-A026-A5CB8AF6E3C1/d/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/private/var/folders/ln/yzs4x7g14wj2f180jqvsbz_w0000gp/T/AppTranslocation/6FA4FDB5-C661-4C99-A026-A5CB8AF6E3C1/d/Atom.app/Contents/Resources/app.asar/src/pane.js:288:22)
    at Pane.module.exports.Pane.activateItem (/private/var/folders/ln/yzs4x7g14wj2f180jqvsbz_w0000gp/T/AppTranslocation/6FA4FDB5-C661-4C99-A026-A5CB8AF6E3C1/d/Atom.app/Contents/Resources/app.asar/src/pane.js:437:21)
    at atom-tabs.TabBarView.onMouseDown (/private/var/folders/ln/yzs4x7g14wj2f180jqvsbz_w0000gp/T/AppTranslocation/6FA4FDB5-C661-4C99-A026-A5CB8AF6E3C1/d/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:681:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
atom-python-run, v0.6.2 (active)
autocomplete-python, v1.8.20 (active)
linter-python-pep8, v0.2.0 (active)
python-debugger, v0.1.0 (active)
python-indent, v1.0.0 (active)
python-suite, v0.3.2 (active)
python-tools, v0.6.8 (active)
qolor, v0.4.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by nrbalajimca** [comment]
Error: This socket is closed
    at Socket._writeGeneric (net.js:673:19)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at checkGrammar (file:///C:/Users/bnr001c/.atom/packages/python-suite/lib/python-suite.coffee:32:33)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\bnr001c\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\bnr001c\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:141:28)
    at C:\Users\bnr001c\AppData\Local\atom\app-1.16.0\resources\app.asar\src\pane-container.js:348:27
    at Pane.module.exports.Pane.observeActiveItem (C:\Users\bnr001c\AppData\Local\atom\app-1.16.0\resources\app.asar\src\pane.js:241:7)
    at C:\Users\bnr001c\AppData\Local\atom\app-1.16.0\resources\app.asar\src\pane-container.js:346:42
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\bnr001c\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\bnr001c\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:141:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (C:\Users\bnr001c\AppData\Local\atom\app-1.16.0\resources\app.asar\src\pane-container.js:198:22)
    at Pane.module.exports.Pane.activate (C:\Users\bnr001c\AppData\Local\atom\app-1.16.0\resources\app.asar\src\pane.js:850:14)
    at Pane.module.exports.Pane.focus (C:\Users\bnr001c\AppData\Local\atom\app-1.16.0\resources\app.asar\src\pane.js:252:21)
    at atom-pane.<anonymous> (C:\Users\bnr001c\AppData\Local\atom\app-1.16.0\resources\app.asar\src\pane-element.js:50:23)
