### ISSUE TITLE
Uncaught SyntaxError: Unexpected token s in JSON at position 0

### ISSUE THREAD

**Issue by Vikash082** [Romaine/python-suite#7]
1. Install python-suite from atom package installer

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [python-suite](https://github.com/Romaine/python-suite) package 0.3.2

### Stack Trace

Uncaught SyntaxError: Unexpected token s in JSON at position 0

```
At file:///usr/share/atom/resources/app/static/index.html:1

SyntaxError: Unexpected token s in JSON at position 0
    at Object.parse (native)
    at Object.updateOutline (/packages/python-suite/lib/python-suite.coffee:46:18)
    at /packages/python-suite/lib/python-suite.coffee:66:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
     -7:24.3.0 core:backspace (input.hidden-input)
  2x -7:21.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-yamljson 0.2.4 
autocomplete-python 1.8.63 
ipython-exec 1.2.0 
python-isort 0.0.7 
python-jedi 0.3.8 
python-run-terminalnx 1.0.3 
python-suite 0.3.2 
python-tools 0.6.9 
remote-atom 1.3.10 
```

**Comment by johannspies** [comment]
I came across the same bug today.
