### ISSUE TITLE
Uncaught TypeError: Cannot read property  item  of undefined

### ISSUE THREAD

**Issue by heavyhadron** [Romaine/python-suite#8]
Enter steps to reproduce:  1. ... 2. ... **Atom**: 1.17.2 x64 **Electron**: 1.3.15 **OS**: Ubuntu 16.04.2 **Thrown From**:  python-suite  https://github.com/Romaine/python-suite  package 0.3.2 ### Stack Trace Uncaught TypeError: Cannot read property  item  of undefined     At /home/user/.atom/packages/python-suite/lib/python-suite.coffee:50 TypeError: Cannot read property  item  of undefined  at Object.updateOutline  /packages/python-suite/lib/python-suite.coffee:50:50   at /packages/python-suite/lib/python-suite.coffee:66:19   at emitOne  events.js:96:13   at Socket.emit  events.js:188:7   at readableAddChunk  _stream_readable.js:176:18   at Socket.Readable.push  _stream_readable.js:134:10   at Pipe.onread  net.js:543:20      ### Commands         ### Non-Core Packages     atom-python-run 0.7.3  highlight-selected 0.13.1  python-debugger 0.2.0  python-suite 0.3.2  python-tools 0.6.9

**Comment by heavyhadron** [comment]
Just upon starting atom, this error is thrown.
